### ISSUE TITLE
Remove hardcoded shard number from prototype

### ISSUE THREAD

**Issue by gabehamilton** [near/queryapi#382]
In the initial prototype where S3 fetch time was a major impediment, number of shards was hardcoded to 4 in the runner. 
https://github.com/near/queryapi/blob/main/runner/src/lake-client/lake-client.ts#L80

Now that we have some pre-fetching strategies let's return to pulling that from the block.json or move it to config.

**Comment by pkudinov** [comment]
Dup[

**Comment by gabehamilton** [comment]
Confirmed that the affected code was fixed in #423

**Comment by morgsmccauley** [comment]
This is still an issue:
- https://github.com/near/queryapi/blob/7655aef45bc4141cc2cc97fdaa0b8ac3fbf09469/runner/src/lake-client/lake-client.ts#L80
- https://github.com/near/queryapi/blob/7655aef45bc4141cc2cc97fdaa0b8ac3fbf09469/block-server/handler.js#L40
